title: "LGR"
author: "Laura Guzman-Rincon"
description: "Last updated<br><b>25 October 2024</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header
navi: false                # include naviagation in sidebar
### TODO: To include navigation (if I want to add more than just home page), will have to sort the menu for non-sidebar view (i.e. mobile)
### To do this, need to add new menu style in _includes (at the moment header and footer use same menu style)

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: Home, file: "index.md", icon = house}
  #- {file: "publications.md"}
  #- {file: "talks.md"}
  #- {file: "teaching.md"}
  #- {file: "software.md"}
  #- {file: "CV.md", title = "CV"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Visit my Github, icon: github, url: "https://github.com/lauraguzmanrincon"}
  - {title: Google scholar, icon: scroll, url: "https://scholar.google.com/citations?user=MxkHD34AAAAJ&hl=en&oi=ao"}
  - {title: Contact me, icon: envelope, url: "mailto:lmg65@cam.ac.uk"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
