title: ""
author: "Laura Guzman-Rincon"
description: "Last updated<br><b>16 November 2023</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", icon = house}
  - {file: "publications.md"}
  - {file: "talks.md"}
  - {file: "teaching.md"}
  - {file: "software.md"}
  - {file: "CV.md", title = "CV"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Contact me, icon: envelope, url: "mailto:laura.guzman-rincon@warwick.ac.uk"}
  - {title: Check out my Github, icon: github, url: "https://github.com/lauraguzmanrincon"}
  - {title: Follow me on X, icon: twitter, url: "https://twitter.com/LGuzmanRincon"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
